name: Sales Management System CI | © 2026

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4   # Nâng cấp lên v4 để hết cảnh báo
      with:
        java-version: '21'          # Đổi thành 21 cho khớp với file pom.xml
        distribution: 'temurin'
        cache: maven

    - name: Build and Run Unit Tests with Maven
      run: mvn -B package --file pom.xml

    - name: Distribute jar-war file
      run: mkdir staging && cp target/*.jar staging

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 1.0-SNAPSHOT
        path: staging
